spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: none

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}