spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${rds.url}
    username: ${rds.username}
    password: ${rds.password}

# JWT 정보
jwt:
  hash-key: ${secret.jwt.hash-key}
  expire-time: ${secret.jwt.expire-time}
  subject: ${secret.jwt.subject}

# 파파고 API 키
papago:
  secret: ${secret.papago.secret}
  id: ${secret.papago.id}

oxford:
  app-id: ${secret.oxford.app-id}
  app-key: ${secret.oxford.app-key}